"use client"

import { useState } from "react"
import DashboardLayout from "@/components/dashboard-layout"
import { StatCard } from "@/components/super-admin/stat-card"
import { StatusBadge } from "@/components/super-admin/status-badge"
import { AdvancedTable } from "@/components/super-admin/advanced-table"
import { ConfirmationDialog } from "@/components/super-admin/confirmation-dialog"
import { Button } from "@/components/ui/button"
import { FileText, Download, Clock, CheckCircle, Plus, FileSpreadsheet } from "lucide-react"
import FormModal from "@/components/form-modal"

interface Report {
  id: string
  reportType: string
  class: string
  generatedDate: string
  status: "Generated" | "Pending" | "Processing"
  generatedBy: string
  fileSize?: string
}

export default function Report() {
  const [reports, setReports] = useState<Report[]>([
    { id: "1", reportType: "Report Card", class: "10-A", generatedDate: "2024-01-15", status: "Generated", generatedBy: "Admin", fileSize: "2.5 MB" },
    { id: "2", reportType: "Academic Report", class: "10-B", generatedDate: "2024-01-16", status: "Generated", generatedBy: "Admin", fileSize: "1.8 MB" },
    { id: "3", reportType: "Attendance Report", class: "9-A", generatedDate: "2024-01-17", status: "Processing", generatedBy: "Admin" },
    { id: "4", reportType: "Fee Report", class: "11-A", generatedDate: "2024-01-18", status: "Generated", generatedBy: "Admin", fileSize: "3.2 MB" },
  ])
  const [isModalOpen, setIsModalOpen] = useState(false)
  const [editingId, setEditingId] = useState<string | null>(null)
  const [deleteConfirm, setDeleteConfirm] = useState<{ open: boolean; id: string | null }>({
    open: false,
    id: null
  })

  const handleAddEdit = (data: any) => {
    if (editingId) {
      setReports(reports.map((r) => (r.id === editingId ? { ...r, ...data } : r)))
      setEditingId(null)
    } else {
      setReports([...reports, { ...data, id: Date.now().toString(), status: "Pending" as const }])
    }
    setIsModalOpen(false)
  }

  const handleDelete = (item: any) => {
    setDeleteConfirm({ open: true, id: item.id })
  }

  const confirmDelete = () => {
    if (deleteConfirm.id) {
      setReports(reports.filter((r) => r.id !== deleteConfirm.id))
    }
    setDeleteConfirm({ open: false, id: null })
  }

  const handleBulkAction = (action: string, selectedIds: string[]) => {
    if (action === "delete") {
      setReports(reports.filter((r) => !selectedIds.includes(r.id)))
    }
  }

  const handleEdit = (item: any) => {
    setEditingId(item.id)
    setIsModalOpen(true)
  }

  const stats = {
    total: reports.length,
    generated: reports.filter(r => r.status === "Generated").length,
    pending: reports.filter(r => r.status === "Pending").length,
    processing: reports.filter(r => r.status === "Processing").length
  }

  const columns = [
    {
      key: "reportType",
      label: "Report Type",
      render: (value: string, row: Report) => (
        <div className="flex items-center gap-3">
          <div className="p-2 bg-blue-100 rounded-lg">
            <FileText className="h-4 w-4 text-blue-600" />
          </div>
          <div>
            <p className="font-medium">{value}</p>
            <p className="text-xs text-muted-foreground">{row.class}</p>
          </div>
        </div>
      )
    },
    {
      key: "generatedDate",
      label: "Generated Date",
      render: (value: string) => new Date(value).toLocaleDateString()
    },
    {
      key: "generatedBy",
      label: "Generated By",
      render: (value: string) => <span className="text-sm">{value}</span>
    },
    {
      key: "fileSize",
      label: "File Size",
      render: (value: string) => value ? <span className="text-sm text-muted-foreground">{value}</span> : <span className="text-xs text-muted-foreground">-</span>
    },
    {
      key: "status",
      label: "Status",
      render: (value: string, row: Report) => (
        <div className="flex items-center gap-2">
          <StatusBadge status={value} />
          {value === "Generated" && (
            <Button size="sm" variant="ghost" className="h-7 px-2">
              <Download className="h-3 w-3" />
            </Button>
          )}
        </div>
      )
    },
  ]

  return (
    <DashboardLayout title="Report">
      <div className="space-y-6">
        <div className="flex justify-between items-center">
          <div>
            <h2 className="text-2xl font-semibold">Report Management</h2>
            <p className="text-sm text-muted-foreground">Generate and manage various reports</p>
          </div>
          <Button onClick={() => { setEditingId(null); setIsModalOpen(true) }}>
            <Plus className="h-4 w-4 mr-2" />
            Generate Report
          </Button>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <StatCard
            title="Total Reports"
            value={stats.total.toString()}
            icon={FileSpreadsheet}
            iconColor="text-blue-600"
            iconBgColor="bg-blue-100"
          />
          <StatCard
            title="Generated"
            value={stats.generated.toString()}
            icon={CheckCircle}
            iconColor="text-green-600"
            iconBgColor="bg-green-100"
          />
          <StatCard
            title="Processing"
            value={stats.processing.toString()}
            icon={Clock}
            iconColor="text-orange-600"
            iconBgColor="bg-orange-100"
          />
          <StatCard
            title="Pending"
            value={stats.pending.toString()}
            icon={FileText}
            iconColor="text-gray-600"
            iconBgColor="bg-gray-100"
          />
        </div>

        <AdvancedTable
          columns={columns}
          data={reports}
          searchable={true}
          searchPlaceholder="Search reports..."
          filterable={true}
          filterOptions={[
            { key: "status", label: "Status", options: ["Generated", "Pending", "Processing"] },
            { key: "reportType", label: "Type", options: [...new Set(reports.map(r => r.reportType))] },
            { key: "class", label: "Class", options: [...new Set(reports.map(r => r.class))] }
          ]}
          selectable={true}
          onEdit={handleEdit}
          onDelete={handleDelete}
          onBulkAction={handleBulkAction}
          pageSize={10}
          emptyMessage="No reports found."
        />

        <FormModal
          isOpen={isModalOpen}
          onClose={() => {
            setIsModalOpen(false)
            setEditingId(null)
          }}
          onSubmit={handleAddEdit}
          title={editingId ? "Edit Report" : "Generate New Report"}
          fields={[
            { name: "reportType", label: "Report Type", type: "select" as const, options: [
              { value: "Report Card", label: "Report Card" },
              { value: "Academic Report", label: "Academic Report" },
              { value: "Attendance Report", label: "Attendance Report" },
              { value: "Fee Report", label: "Fee Report" },
              { value: "Performance Report", label: "Performance Report" },
              { value: "Topic Report", label: "Topic Report" },
              { value: "Lesson Planner Report", label: "Lesson Planner Report" }
            ], required: true },
            { name: "class", label: "Class", type: "text" as const, required: true },
            { name: "generatedDate", label: "Generated Date", type: "date" as const, required: true },
            { name: "generatedBy", label: "Generated By", type: "text" as const, required: true },
            { name: "status", label: "Status", type: "select" as const, options: [
              { value: "Generated", label: "Generated" },
              { value: "Pending", label: "Pending" },
              { value: "Processing", label: "Processing" }
            ], required: true },
          ]}
          initialData={editingId ? reports.find((r) => r.id === editingId) : {}}
        />

        <ConfirmationDialog
          open={deleteConfirm.open}
          onOpenChange={(open) => setDeleteConfirm({ open, id: null })}
          title="Delete Report"
          description="Are you sure you want to delete this report? This action cannot be undone."
          onConfirm={confirmDelete}
          confirmText="Delete"
          variant="destructive"
        />
      </div>
    </DashboardLayout>
  )
}
